name: CI

on:
  push:
    branches: [ main, stage, devel ]
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Github Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
